# Generated by Django 5.1.4 on 2024-12-25 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retail_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemtype',
            name='id',
        ),
        migrations.AlterField(
            model_name='itemtype',
            name='type_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
