# Generated by Django 5.1.4 on 2024-12-25 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retail_app', '0002_remove_itemtype_id_alter_itemtype_type_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('company_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=255)),
                ('company_contact', models.CharField(max_length=255)),
                ('company_email', models.EmailField(max_length=254)),
                ('company_address', models.TextField()),
            ],
        ),
    ]
