# Generated by Django 5.1.4 on 2024-12-25 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retail_app', '0003_companyinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Salesman',
            fields=[
                ('salesman_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('salesman_name', models.CharField(max_length=255)),
                ('salesman_contact', models.CharField(max_length=254)),
                ('company_id', models.BigIntegerField()),
            ],
        ),
    ]
