# Generated by Django 5.1.4 on 2024-12-30 07:06

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retail_app', '0006_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockTracking',
            fields=[
                ('tracking_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tracking_stock_in', models.IntegerField(default=0)),
                ('tracking_stock_out', models.IntegerField(default=0)),
                ('tracking_current_stock', models.IntegerField()),
                ('tracking_transaction_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('tracking_remarks', models.TextField(blank=True, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='retail_app.inventory')),
            ],
        ),
    ]
