# Generated by Django 5.1.4 on 2024-12-30 07:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retail_app', '0007_stocktracking'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockExpiry',
            fields=[
                ('expiry_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('manufacture_date', models.DateField()),
                ('expiry_date', models.DateField()),
                ('quantity_expiry', models.BigIntegerField()),
                ('expiry_status', models.IntegerField(default=1)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='retail_app.inventory')),
            ],
        ),
    ]
