# Generated by Django 5.1.4 on 2024-12-31 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retail_app', '0010_orderitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='item_id',
            new_name='item',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='order_id',
            new_name='order',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order_item_quantity',
            field=models.PositiveIntegerField(),
        ),
    ]
