# Generated by Django 5.1.4 on 2024-12-31 09:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retail_app', '0011_rename_item_id_orderitem_item_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wastage',
            fields=[
                ('wastage_id', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('quantity_ordered', models.PositiveIntegerField()),
                ('quantity_received', models.PositiveIntegerField()),
                ('quantity_wasted', models.PositiveIntegerField()),
                ('reason_for_wastage', models.CharField(choices=[('Damage', 'Damage'), ('Spoilage', 'Spoilage'), ('Expiration', 'Expiration'), ('Other', 'Other')], max_length=50)),
                ('date_of_wastage', models.DateTimeField(auto_now_add=True)),
                ('return_status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Returned', 'Returned')], default='Pending', max_length=50)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='retail_app.inventory')),
            ],
        ),
    ]
