# Generated by Django 5.1.4 on 2024-12-31 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retail_app', '0012_wastage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wastage',
            name='wastage_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
