# Generated by Django 5.1 on 2025-01-13 07:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retail_app', '0015_salesmaninfo_alter_stock_salesman_delete_salesman'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('item_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=255)),
                ('item_status', models.IntegerField(choices=[(1, 'Active'), (0, 'Inactive')], default=1)),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='retail_app.companyinfo')),
                ('type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='retail_app.item_type')),
            ],
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='retail_app.products'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='retail_app.products'),
        ),
        migrations.AlterField(
            model_name='stockexpiry',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='retail_app.products'),
        ),
        migrations.AlterField(
            model_name='stocktracking',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='retail_app.products'),
        ),
        migrations.AlterField(
            model_name='wastage',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='retail_app.products'),
        ),
    ]
