# Generated by Django 5.1.4 on 2025-01-13 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retail_app', '0016_products_alter_orderitem_item_alter_stock_item_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('return_reason', models.TextField()),
                ('return_date', models.DateField()),
                ('reason', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='wastage',
            name='item',
        ),
        migrations.CreateModel(
            name='OrderReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_reason', models.TextField()),
                ('return_date', models.DateField()),
                ('reason', models.CharField(max_length=255)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='retail_app.order')),
            ],
        ),
        migrations.DeleteModel(
            name='Inventory',
        ),
        migrations.DeleteModel(
            name='Wastage',
        ),
    ]
