# Generated by Django 5.1.4 on 2025-01-14 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retail_app', '0017_companyreturn_remove_wastage_item_orderreturn_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CompanyReturn',
        ),
        migrations.RemoveField(
            model_name='orderreturn',
            name='reason',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='order_item_discount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Discount (%)'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='order_item_subtotal',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='order_item_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='products',
            name='item_formula',
            field=models.CharField(default='default_formula', max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='products',
            name='item_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='stockexpiry',
            name='batch_no',
            field=models.CharField(default='Batch No', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='company_contact',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='company_email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='company_name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='item_type',
            name='type_name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order_item_quantity',
            field=models.PositiveIntegerField(verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order_item_unitprice',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='products',
            name='item_name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
