# Generated by Django 5.1.4 on 2025-01-15 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retail_app', '0019_remove_orderitem_order_orderitem_order_customer_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='order_item_description',
            field=models.TextField(default='No description available'),
        ),
    ]
